server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: service1
          uri: http://localhost:8081
          predicates:
            - Path=/api/service1/**
        - id: service2
          uri: http://localhost:8082
          predicates:
            - Path=/api/service2/**
        - id: service3
          uri: http://localhost:8083
          predicates:
            - Path=/api/service3/**